apiVersion: v1
kind: Pod
metadata:
  name: queue-pod
  labels:
    app: queue-pod
spec:
  containers:
  - name: queue
    image: redis:3.2
    ports:
    - containerPort: 6379
    readinessProbe:
      exec:
        command:
        - "[ $$(redis-cli ping) = \"PONG\" ] || exit 1"
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 5
