apiVersion: v1
kind: Pod
metadata:
  name: vote-pod
  labels:
    app: vote-pod
spec:
  containers:
  - name: vote
    image: vote
    ports:
    - containerPort: 3000
  readinessProbe:
    exec:
      command:
      - "curl"
      - "-f"
      - "http://localhost"
    timeoutSeconds: 1
    periodSeconds: 5
    failureThreshold: 10
