apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    app: worker-pod
spec:
  containers:
  - name: worker
    image: worker
    imagePullPolicy: IfNotPresent
    env:
    - name: DATABASE_HOST
      value: "database.default.svc.cluster.local"
    - name: DATABASE_PORT
      value: "27017"
    - name: QUEUE_HOST
      value: "queue.default.svc.cluster.local"
    - name: QUEUE_PORT
      value: "6379"
