version: '2.1'

networks:
  test_net:
    driver: bridge

services:

  sut:
    image: worker
    entrypoint: node_modules/mocha/bin/mocha --ui tdd test/test.js 
    networks:
      - test_net
    depends_on:
      - worker

  worker:
    build: .
    image: worker
    environment:
      - DATABASE_NAME=worker_test_db
    networks:
      - test_net
    depends_on:
      - queue
      - database

  queue:
    image: redis:3.2
    networks:
      - test_net

  database:
    image: mongo:3.6
    networks:
      - test_net
