version: '2.1'

networks:
  test_net:
    driver: bridge

services:

  sut:
    image: vote
    entrypoint: node_modules/mocha/bin/mocha --ui tdd test/test.js 
    networks:
      - test_net
    depends_on:
      - vote

  vote:
    build: .
    image: vote
    environment:
      - DATABASE_NAME=worker_test_db
    networks:
      - test_net
    depends_on:
      - database
      - queue
      - worker

  worker:
    image: subfuzion/vote-worker
    environment:
      - DATABASE_NAME=worker_test_db
    networks:
      - test_net
    depends_on:
      - queue
      - database

  database:
    image: mongo:3.4
    networks:
      - test_net

  queue:
    image: redis:3.2
    networks:
      - test_net

