version: '2.1'

networks:
  test_net:
    driver: bridge

services:

  sut:
    build: .
    command: test
    networks:
      - test_net
    depends_on:
      - database
      - queue
#      database:
#        condition: service_healthy
#      queue:
#        condition: service_healthy

  database:
    image: mongo:3.4
    networks:
      - test_net

  queue:
    image: redis:3.2
    networks:
      - test_net

