Database:
  Name: database
  Image: "mongo"
  ImageTag: "3.4"
  Replicas: 1
  Component: "database"
  ServicePort: 27017
  ContainerPort: 27017
Queue:
  Name: queue
  Image: "redis"
  ImageTag: "3.2"
  Replicas: 1
  Component: "queue"
  ServicePort: 6379
  ContainerPort: 6379
Vote:
  Name: vote
  Image: "vote"
  ImageTag: "latest"
  Replicas: 1
  Component: "vote"
  ServicePort: 3000
  ContainerPort: 3000
Worker:
  Name: worker
  Image: "worker"
  ImageTag: "latest"
  Replicas: 1
  Component: "worker"
