apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: NodePort
  selector:
    app: vote
  ports:
  - port: {{ .Values.Vote.ServicePort }}
    targetPort: {{ .Values.Vote.ContainerPort }}
