apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "vote-fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Vote.Component }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  backend:
    serviceName: vote
    servicePort: {{ .Values.Vote.ServicePort }}
